### ISSUE TITLE
Implied incorrect Zephyr value

### ISSUE THREAD

**Issue by ljosberinn** [acornellier/not_even_close#1]
thanks for making this, love it :) noticed 2 small issues however:

- BRH Shadow Bolt Volley is not AoE
- Throne Shock Blast despite having the `Treat as Area of Effect` flag is not AoE. from what I found out, it's for the circle around you and/or the orbs emanating from it
- could add last boss Everbloom, not only because of the aoe damage outside of add phase being dangerous already but also accounting for add being up

**Comment by acornellier** [comment]
- Shadow Bolt Volley is AoE, I confirmed it here https://www.reddit.com/r/CompetitiveWoW/comments/18ws88w/comment/kgbgogd/?utm_source=share&utm_medium=web2x&context=3
- I'm pretty sure Shock Blast is also AoE, you can see here https://www.warcraftlogs.com/reports/cpJ9gkwaCWZP7DRG#fight=6&type=damage-taken&ability=428041&view=events
- Sure!
