### ISSUE TITLE
Calming Prescence

### ISSUE THREAD

**Issue by ariassh** [acornellier/not_even_close#2]
Monk Talent Calming Prescence says 6% DR but its 3%
https://www.wowhead.com/spell=388664/calming-presence#news
https://www.wowhead.com/talent-calc/monk/windwalker/DACAEAAA

**Comment by acornellier** [comment]
It's 6% for mistweaver and 3% for windwalker/BM
https://www.wowhead.com/news/dragonflight-patch-10-2-guardians-of-the-dream-official-patch-notes-335731
