### ISSUE TITLE
Sanctified Plates

### ISSUE THREAD

**Issue by ariassh** [acornellier/not_even_close#3]
Sanctified Plates has 5/10% DR as Retribution Paladin and Protection Paladin
It is 3%/6% as Holy Paladin
![image](https://github.com/acornellier/not_even_close/assets/1903074/7d3bb68e-44e1-4d1d-a6e2-5e2022adff70)
![image](https://github.com/acornellier/not_even_close/assets/1903074/b1b631d9-51c8-432d-9315-775b346133cc)
![image](https://github.com/acornellier/not_even_close/assets/1903074/e280b695-da77-47e0-b953-b138706ae4b2)

**Comment by acornellier** [comment]
Oh god I was completely off, thanks a lot. I just pushed the fix. Wowhead is so unreliable https://www.wowhead.com/spell=402964/sanctified-plates
